CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS staff (
  id UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  phone_number VARCHAR(16) NOT NULL,
  name VARCHAR(50) NOT NULL,
  password VARCHAR(60) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
