BEGIN;

CREATE TABLE IF NOT EXISTS transactions (
  id VARCHAR(26) PRIMARY KEY NOT NULL,
  customer_id VARCHAR(26) NOT NULL,
  total_price INT NOT NULL DEFAULT 0,
  paid INT NOT NULL DEFAULT 0,
  change INT NOT NULL DEFAULT 0,
  is_deleted BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

COMMIT;