name: eniqilo-store-restful-api

services:
  db:
    image: postgres:16.3
    restart: always
    container_name: eniqilo-store-pg
    hostname: ${DB_HOST}
    networks:
      - eniqilo-store-pg-net
    ports:
      - 5433:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME}']
      interval: 30s
      timeout: 30s
      retries: 5

  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    container_name: eniqilo-store-migrate
    networks:
      - eniqilo-store-pg-net
    volumes:
      - ./db/migrations:/migrations
    command:
      [
        '-database',
        'postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?${DB_PARAMS}',
        '-path',
        '/migrations',
        '-verbose',
        'up',
      ]

  server:
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    image: danzbraham/eniqilo-store
    restart: on-failure
    container_name: eniqilo-store-server
    hostname: eniqilo-store-server
    networks:
      - eniqilo-store-pg-net
    ports:
      - 8080:8080
    environment:
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PARAMS=${DB_PARAMS}
      - JWT_SECRET=${JWT_SECRET}
      - BCRYPT_SALT=${BCRYPT_SALT}

volumes:
  pg-data:

networks:
  eniqilo-store-pg-net:
    driver: bridge
